// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/geraldiadityo/go-backend/internal/config"
	"github.com/geraldiadityo/go-backend/internal/modules/auth"
	"github.com/geraldiadityo/go-backend/internal/modules/pegawai"
	"github.com/geraldiadityo/go-backend/internal/modules/role"
	"github.com/geraldiadityo/go-backend/internal/modules/users"
)

// Injectors from wire.go:

func InitializeApp() (*Server, error) {
	appConfig := config.LoadConfig()
	db := config.ProvideDB(appConfig)
	repository := pegawai.NewRepository(db)
	service := pegawai.NewService(repository)
	handler := pegawai.NewHandler(service)
	router := pegawai.NewRouter(handler, db)
	roleRepository := role.NewRepository(db)
	roleService := role.NewService(roleRepository)
	roleHandler := role.NewHandler(roleService)
	roleRouter := role.NewRouter(roleHandler, db)
	usersRepository := users.NewRepository(db)
	usersService := users.NewService(usersRepository, service, roleService)
	usersHandler := users.NewHandler(usersService)
	usersRouter := users.NewRouter(usersHandler, db)
	authService := auth.NewService(usersService, appConfig)
	authHandler := auth.NewHandler(authService)
	authRouter := auth.NewRouter(authHandler)
	server := NewServer(router, roleRouter, usersRouter, authRouter, appConfig, db)
	return server, nil
}
